events { worker_connections 1024; }

http {
    # 这一行是解决问题的核心！
    # 127.0.0.11 是 Docker 内部固定的 DNS 服务器地址
    resolver 127.0.0.11 ipv6=off;

    # 包含默认路径和我们自定义的 lualib 路径
    lua_package_path "/usr/local/openresty/nginx/lualib/?.lua;/usr/local/openresty/lualib/?.lua;;";
    
    # 必须项：用于集群 Slot 锁定
    lua_shared_dict redis_cluster_slot_locks 100k;

    server {
        listen 80;

        location /api {
            default_type application/json;
            content_by_lua_file /usr/local/openresty/nginx/lua/cache_logic.lua;
        }

        # 模拟后端，生产环境这里换成你的真实业务地址
        location /_backend {
            internal;
            return 200 '{"status":"success", "data":"This is from Backend API"}';
        }
    }
}
